### ISSUE TITLE
Extremely slow, causing Sketch to hang

### ISSUE THREAD

**Issue by yorb** [eivindbohler/Sketch-Unlinker#1]
First of all, this plugin is exactly what I wanted, so kudos. :)

Unfortunately, it's been extremely slow for me, even on groups with just a few dozen layers. It beachballs and I end up having to force quit. Even when only a handful of symbols were selected, it's taking 5+ minutes for me (but it does ultimately finish).

Any idea what's going on?

**Comment by eivindbohler** [comment]
Which version of Sketch are you currently on? And what hardware are you using? I've used the script on pretty massive documents without ever having experienced the slowdowns you describe - do you have any public Sketch documents that I can try where you see this issue? Thanks! :)

**Comment by peach93** [comment]
I have the same problem everytime I want to unlink something. I actually love your plug-in and need it every single day. Do you have any idea? I use the newest Sketch Version, updated it today. In the actual and the previous version the plug-in is very slow...
Greetings Caro

**Comment by eivindbohler** [comment]
@yorb @peach93 I've updated the script - version 1.1 should be 1-2 orders of magnitude faster, give it a try!

**Comment by peach93** [comment]
Thanks @eivindbohler! It works very well now :)
